# Installing everything together seems to not work
# So before everything install numpy then tensorflow-gpu then
# update the environment with this stuff
#
# conda install numpy=1.23
# conda install tensorflow-gpu=2.6.0

channels:
  - conda-forge
  - anaconda
dependencies:
  - uvicorn
  - fastapi
  - fastapi_utils
  - more-itertools
  - requests
  - tqdm
  - termcolor
  - pip:
      - pymitter==0.4.0
